package enumTypes;

public enum DatabaseTablesName {
    ABSENCES, ADMIN, CLASS, EMAIL, FINAL_GRADE, GUARDIAN, LESSON, MARK, NOTES, PLAN, PRINCIPAL, SCHOOL, SCHOOL_SUBJECT,
    STUDENT, TEACHER, USER
}
